module.exports = {
    bot: function() {
       return [    
       "cc" ,
       "đồ con chó",
       "clon" ,
       "đm dm duma",
       "địt" ,
       "mồm",
       "chu mỏ lồn" ,
       "súc vật" ,
       "Địt tằng tằng" ,
       "mặt lòn" ,
       "xử",
       "Thằng mặt tó buồi cặc Cẹc" ,
       "vãi lồn lôz"  ,
       "fuck "  ,
       "cặc"  ,
       "lòn lồn loz lôz lồz" ,
       "coconut pussy",
       "đĩ",
       "dis" ,
       "bể đầu" ,
       "dậy thì",
       "Hãm",
       "l**",
       "mương",
       "Định mệnh",
       "đcm đmcs đkm djt Đ!t cmn" ,
       "Đánh lộn" ,
       "Đá chết họa mi mày giờ",
       "chửi người ta",
       "đmcs" ,
       "cocc",
       "chơi gái phò",
       "Gái ngành",
       "Lần đầu",
       "#ĐMCS #đmcs" ,
       "thằng con cán bộ" ,
       "đụ má Đụ moá đụ mọe" ,
       "nường" ,
       "dánh" ,
       "ke" ,
       "nốc" ,
       "dốc" ,
       "đốc" ,
       "Uống thuốc tránh thai",
       "Đồ trong đồ lót",
       "đò đỏ" ,
       "LẨY THÈ LE TÈ LE" ,
       "nõ" ,
       "lõ" ,
       "nọc cọc chông" ,
       "ngoi đít vịt" ,
       "làm dĩ đĩ đũy đỉ điếm địt",
       "ke que buồi cặc chông chim cò cu" ,
       "ghe",
       "thông đít",
       "nulo",
       "Cút xéo phánh",
       "vãi clg clq",
       "LẸO Cước Chú" ,
       "such ass" ,
       "what life"  ,  
       "Shut up cunt" ,
       "ĐCM" ,
       "tiên sư cha mày" ,
       'mẹ đĩ nợ',
       "Bitch",
       "vcl",
       "Chink",
       "Đù",
       "Đạp mày nát bét",
       "Đéo",
       "Đè bẹp mày",
       "Khinh tao",
       "con cặc",
       "bướm",
       "phò cẩu sanh",
       "khốn nạn",
       "chó cho thằng thang",
       "tụi bây tao ta",
       "Chink Dickhead Haizzz Dyke Fag faggot Gook Limey Motherfucker Queer Sucker Whore Slut Drop dead bastard Dick Rip Pennis" ,
       "lột đồ nhau" ,
       "Cộng Sản Quần Què #DMCS Bò Đỏ con cặc shut fuck STFU #STFU suck my dick Penis Pussy pussy Việt Nam Cộng Hoà muôn năm Đảng Lồn bợ đít nâng bi cái lồn KHÍ ĐỤ mặt cặc pussy face chó địt bú buồi liếm cu bú lồn cành cạch nứng lồn quện đĩ chó Sấp Mặt Lồn Định kiến khắc nghiệt ưng đụ tao à cái đĩ mẹ đá phò dòng đĩ cốt cách phò năng đĩ cộng sản đĩ cách mạng nứng lồn bóng long xiên địt moẹ moài lồn đĩ nứng lồn chim hưng phấn nứng lồn mong manh chịch bú cu thông đít Bash óc chó ngu chó óc lồn đầu khấc nứng lồn cộng sản pussy wet sục cặc hột le"];
    }
}