module.exports = {
    bot: function() {
       return {
        "Thứ phò cẩu":"1",
        "Con cẩu sanh":"1",
        "Bươm bướm dối trá":"1",
        "Nhớ gia đình ạ":"0",
        "Bản thân của ngày xưa":"0",
        "Gặt hái được nhiều thành công":"0",
        "May mắn lắm đó nha":"0",
        "Tui nói ông nghe nè, tui yêu ông":"0",
        "Thương em là điều anh không thể ngờ":"0",
        "em muốn uống trà sữa":"0",
        "xịt sữa":"1",
        "bình thường, cx ko hay chi mấy.":"0",
        "Thay ava chào năm mới cho đỡ mốc":"0",
        "100 là đổi từ 85% ra 85 phần 100 đó bạn":"0",
        "Hay!":"0",
        "chính sách trả góp như thế nào ạ ?":"0",
        "Ngầu =))))":"0",
        "vai lolll":"1",
        "chó":"1",
        "cười ị":"1",
        "đĩ mọe mày":"1",
        "Muốn đụ tui hay gì":"1",
        "Gay porn":"1",
        "wtf":"1",
        "Con đĩ lồn":"1",
        "Đừng có làm cái lồn như vậy nữa":"1",
        "t lạy dưới lol t lạy lên":"1",
        "duma đỉnh":"1",
        "học để xử mấy mẹ hàng xóm":"1",
        "quá đáng": "1",
        "Khỏi sợ cưng, cưng dính chị có cách": "0",
        "Bitch naneun solo": "1",
        "Ngành IoT trong chương trình đào tạo của FPoly": "0",
        "Yêu hay không yêu, không yêu hay yêu nói một lời": "0",
        "Tổ cha mi": "1",
        "Đời tôi là một vườn hoa lá": "0",
        "Chỉ muốn vậy": "0",
        "Bắt đầu chuỗi ngày mang kính": "0",
        "Chó Hoang mà cứ nghĩ mình là Bà Hoàng của xã hội": "1",
        "Bản chất mày mất dạy": "1",
        "Ai khóc nỗi đau này": "0",
        "Đã ngu mà còn cố tỏ ra nguy hiểm": "1",
        "Một khi đã ghét thì chỉ muốn dẫm và đạp cho nát bét là xong. Còn một khi đã khinh, thì chỉ lặng thinh và coi như đéo tồn tại": "1",
        "Chúng ta ko thể chống lại những thằng ngu bởi vì chúng quá đông và nguy hiểm": "1",
        "Tao không có gì ngoài điều kiện nghe mi": "1",
        "Em làm gì đã có người yêu, em đang sợ ế đây này": "0",
        "Mày chết đi sống làm gì nữa": "1",
        "Chàng trai của em, em yêu anh rất nhiều": "0",
        "Anh không ngại việc ra Hà Nội. Anh chỉ cần có lý do thôi": "0",
        "Cuộc sống mà": "0",
        "Thương thì nói rằng thương nha, đừng ấp úng nữa!": "0",
        "Dân thường chơi đẹp đè bẹp dân chơi": "1",
        "Chỉ muốn như vậy mãi thôi": "0",
        "Tổ lái": "0",
        "Đen đá không đường nha mấy cưng": "0",
        "Chạy ngay đi": "0",
        "Thanh xuân của anh viết tắt là em đó, yêu em!": "0",
        "Quỳnh ơi! Dượng đây!": "0",
        "Qua những ngày xuân": "0",
        "Thương ai nói đi đừng ngại": "0",
        "Độ ta không độ nàng":"0",
        "Anh không thể biến mùa hạ thành đông nhưng cũng không thể khiến em về bên anh": "0",
        "Những người anh em thiện lành của chúng ta đó": "1",
        "Lần đầu tiên đi chơi gái":"1",
        "Đặt chân đến chốn này":"0",
        "Đẹp tuyệt":"0",
        "mẹ cái con đĩ":"1",
        "Quá hay":"0",
        "Tuổi thơ":"0",
        "Có tour bắt đầu ở đà nẵng ko zậy ad":"0",
        "Đến đà nẵng ăn đặc sản trần":"0",
        "Quà bé ơi":"0",
        "Xinh quá trời ơi chị ơi":"0",
        "KHÍ ĐỤ":"1",
        "dume y chang":"1",
        "Giờ l** cũng có gai":"1",
        "t nghĩ lớp 7 t đi làm đĩ":"1",
        "Ghét mấy đĩ ảo ghê":"1",
        "Đừng có xạo lồz":"1",
        "coconut pussy":"1",
        "Đụ má bài người ta làm":"1",
        "bitch giọng mẹ ghe":"1",
        "dm":"1",
        "chửi người ta mà mày ziên ghê đĩ":"1",
        "Haizzz thứ khốn nạn tụi bây":"1"
       }
    }
}