module.exports = {
    bot: function() {
       return {
        "Mắt biếc nay còn đâu":"0",
        "Hy vọng phim sẽ đóng đạt, ko cắt xén như các tác phẩm chuyển thể khác":"0",
        "Đời Mị còn trẻ":"1",
        "Tôi muốn làm người lương thiện nhưng ai cho tôi lương thiện":"1",
        "Định kiến khắc nghiệt vừa thôi mấy má":"1",
        "Trong CLB Khoa học kỹ thuật mình đã upload các bài đăng chứa link đến các kho lưu trữ bao gồm code, tài liệu và dự án rồi nhé, ai muốn xem hãy tham gia ngay nào":"0",
        "Cuộc đời......ko có màu hồng ":"0",
        "Hãy trao cho anh":"0",
        "Đang chạy bo":"0",
        "Mìnhhh đã từng là của nhau và đã yêu nhau thật đậm sâu":"0",
        "Thứ anh đang mong chờ....":"0",
        "Thấy quen quen, hình như chơi trò này đâu đó rồi ? temple run ?":"0",
        "Nó lại quá đúng":"0",
        "Có điểm chuẩn rồi nhé , xem thử thăng hoa hay bế tắc":"0",
        "Năm sau là tới lượt mình hòa chung không khí này":"0",
        "Cuối cùng cũng xong ":"0",
        "Bọn mày nghĩ sao về việc quay lại với người yêu cũ?":"0",
        "Tỉnh giấc mộng đi các ông":"0",
        "Ngầu vcl luôn mấy má ơi":"1",
        "Tóc đuôi cá thần thánh thời trẩu":"0",
        "Xạo lồn":"1",
        "Hãy Yêu Chàng Trai Không Cho Bạn Uốn Viên Thuốc Này":"1",
        "Cái địt mẹ em chứ":"1",
        "Có tâm vl hì":"1",
        "Có mang đồ trong không?":"1",
        "Ngây ngô đáng yêu":"0",
        "Nắng sao chói bằng hào quang quanh em":"0",
        "Sao hồi đó mình duyên vậy ta":"0",
        "Ngủ ngon nha":"0",
        "Ta ghiền ăn lắm":"0",
        "Cái nghi thức lôz":"1",
        "Nóng vãi lồn":"1",
        "Chán vãi lồn":"1",
        "Thời tiết như lồn":"1",
        "Lải nhải cái lồn":"1",
        "Thằng mặt lồn":"1",   
        "Xạo lồn":"1",
        "Sướng vãi cả lồn":"1",
        "Vãi lồn":"1",             
        "Thứ phò cẩu":"1",
        "Con cẩu sanh":"1",
        "Bươm bướm dối trá không thấy ngượng mồm":"1",
        "Nhớ gia đình ạ":"0",
        "Sắp vào năm học rồi, ôn bài thôi nào":"0",
        "Bản thân của ngày xưa":"0",
        "Gặt hái được nhiều thành công":"0",
        "May mắn lắm đó nha":"0",
        "Tui nói ông nghe nè, tui yêu ông":"0",
        "Thương em là điều anh không thể ngờ":"0",
        "em muốn uống trà sữa":"0",
        "xịt sữa":"1",
        "bình thường, cx ko hay chi mấy.":"0",
        "Thay ava chào năm mới cho đỡ mốc":"0",
        "100 là đổi từ 85% ra 85 phần 100 đó bạn":"0",
        "Hay!":"0",
        "chính sách trả góp như thế nào ạ ?":"0",
        "Ngầu =))))":"0",
        "vai lolll":"1",
        "chó":"1",
        "cười ị":"1",
        "đĩ mọe mày":"1",
        "Muốn đụ tui thì thả Haha nha":"1",
        "Gay porn":"1",
        "wtf ":"1",
        "Con đĩ lồn":"1",
        "Đừng có làm cái lồn như vậy nữa":"1",
        "t lạy dưới lol t lạy lên":"1",
        "duma đỉnh":"1",
        "học để xử mấy mẹ hàng xóm":"1",
        "quá đáng": "1",
        "Khỏi sợ cưng, cưng dính chị có cách": "1",
        "Bitch naneun solo": "1",
        "Ngành IoT trong chương trình đào tạo của FPoly": "0",
        "Yêu hay không yêu, không yêu hay yêu nói một lời": "0",
        "Tổ cha mi": "1",
        "lạy từ lòn lạy lên":"1",
        "nứng cặc hay gì":"1",
        "Đời tôi là một vườn hoa lá": "0",
        "Chỉ muốn vậy": "0",
        "Bắt đầu chuỗi ngày mang kính": "0",
        "Chó Hoang mà cứ nghĩ mình là Bà Hoàng của xã hội": "1",
        "Bản chất mày mất dạy": "1",
        "Ai khóc nỗi đau này": "0",
        "Đã ngu mà còn cố tỏ ra nguy hiểm": "1",
        "Một khi đã ghét thì chỉ muốn dẫm và đạp cho nát bét là xong. Còn một khi đã khinh, thì chỉ lặng thinh và coi như đéo tồn tại": "1",
        "Chúng ta ko thể chống lại những thằng ngu bởi vì chúng quá đông và nguy hiểm": "1",
        "Tao không có gì ngoài điều kiện nghe mi": "1",
        "Em làm gì đã có người yêu, em đang sợ ế đây này": "0",
        "Mày chết đi sống làm gì nữa": "1",
        "Chàng trai của em, em yêu anh rất nhiều": "0",
        "Anh không ngại việc ra Hà Nội. Anh chỉ cần có lý do thôi": "0",
        "Cuộc sống mà": "0",
        "Thương thì nói rằng thương nha, đừng ấp úng nữa!": "0",
        "Dân thường chơi đẹp đè bẹp dân chơi": "1",
        "Chỉ muốn như vậy mãi thôi": "0",
        "Tổ lái": "0",
        "Đen đá không đường nha mấy cưng": "0",
        "Chạy ngay đi": "0",
        "Thanh xuân của anh viết tắt là em đó, yêu em!": "0",
        "Quỳnh ơi! Dượng đây!": "0",
        "Qua những ngày xuân": "0",
        "Thương ai nói đi đừng ngại": "0",
        "Độ ta không độ nàng":"0",
        "Anh không thể biến mùa hạ thành đông nhưng cũng không thể khiến em về bên anh": "0",
        "Những người anh em thiện lành của chúng ta đó": "1",
        "Lần đầu tiên đi chơi gái":"1",
        "Đặt chân đến chốn này":"0",
        "Đẹp tuyệt":"0",
        "mẹ cái con đĩ":"1",
        "Quá hay":"0",
        "Tuổi thơ":"0",
        "Có tour bắt đầu ở đà nẵng ko zậy ad":"0",
        "Đến đà nẵng ăn đặc sản trần":"0",
        "Quà bé ơi":"0",
        "Xinh quá trời ơi chị ơi":"0",
        "KHÍ ĐỤ":"1",
        "dume y chang":"1",
        "Giờ l** cũng có gai":"1",
        "t nghĩ lớp 7 t đi làm đĩ":"1",
        "Ghét mấy đĩ ảo ghê":"1",
        "Đừng có xạo lồz":"1",
        "coconut pussy":"1",
        "Đụ má bài người ta làm":"1",
        "bitch giọng mẹ ghe":"1",
        "dm":"1",
        "chửi người ta mà mày ziên ghê đĩ":"1",
        "Haizzz thứ khốn nạn tụi bây":"1",
        "Đi làm gái ngành":"1"
       }  
    }
}